package UI;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TabPane;

import javafx.scene.layout.FlowPane;

import javafx.scene.control.Tab;

import javafx.scene.control.RadioButton;

import javafx.scene.control.PasswordField;

import javafx.scene.control.Hyperlink;

import javafx.scene.layout.Pane;

public class MainController {
	@FXML
	private TabPane tabs;
	@FXML
	private Tab history;
	@FXML
	private FlowPane wrappingList;
	@FXML
	private Hyperlink onlineHelp;
	@FXML
	private Hyperlink importPic;
	@FXML
	private Button takePic;
	@FXML
	private Button verifye;
	@FXML
	private Button predict;
	@FXML
	private Button experiment;
	@FXML
	private Tab stats;
	@FXML
	private Pane chart;
	@FXML
	private Tab admin;
	@FXML
	private TextField name;
	@FXML
	private PasswordField pwd;
	@FXML
	private RadioButton remember;
	@FXML
	private Button logIn;

	// Event Listener on Hyperlink[#importPic].onAction
	@FXML
	public void openPicker(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#verifye].onAction
	@FXML
	public void verify(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#predict].onAction
	@FXML
	public void predict(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#experiment].onAction
	@FXML
	public void experiment(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#remember].onAction
	@FXML
	public void remember(ActionEvent event) {
		// TODO Autogenerated
	}
}
